### ISSUE TITLE
Symfony Configuration

### ISSUE THREAD

**Issue by WeTurkstra** [LYDIC-GROUP/rapid-api-crud-bundle#2]
Add a configuration file based on: https://symfony.com/doc/current/components/config/definition.html

We need to add configuration for Bundle wide settings: 
- Define the controller config defaults.
- FilterMode

Example: 
```yaml
rapidcrud:
  controller:
    listEnabled: true
    findEnabled: true
    etc....
    filterMode: BASIC/EXTENDED
```

More suggestions for the configuration are welcome.
